### ISSUE TITLE
I still keep getting ads. I'm I doing something wrong?

### ISSUE THREAD

**Issue by dawoodjee** [Nuzair46/SpotX-Mac#65]
<img width="572" alt="image" src="https://github.com/Nuzair46/SpotX-Mac/assets/7912989/078d7174-576e-4634-9911-4e50885b628e">

<img width="1263" alt="image" src="https://github.com/Nuzair46/SpotX-Mac/assets/7912989/aa328172-fb47-4da9-87d9-a2c10c3493d3">

I'm on macos intel

<img width="487" alt="image" src="https://github.com/Nuzair46/SpotX-Mac/assets/7912989/ab4f2bc7-5989-47f4-a761-7554e7aa7ea7">

Any ideas or tests I should check?

**Comment by Nuzair46** [comment]
likely an issue with new update. will look into this over the weekend

**Comment by nakheel77** [comment]
> likely an issue with new update. will look into this over the weekend

Many thanks for update!

**Comment by tikumo** [comment]
Ran the script thursday, perhaps they found a way to unblock this blocker. 
Hope you find it! 

![image](https://github.com/Nuzair46/SpotX-Mac/assets/559615/3e5975d1-728f-4b82-b5d2-b7bf05337696)

**Comment by jiwaCh** [comment]
any update? 

or alternative project?

**Comment by Nuzair46** [comment]
Sorry. Give me some time. In the meantime feel free to use the alternative

**Comment by skupjoe** [comment]
https://github.com/SpotX-Official/SpotX-Bash

This project works on Mac + Linux for latest version. Confirmed both on Apple Silicon + Intel.

@Nuzair46 no disrespect, thank you for all your work here, but wondering why continue to support this fork and not centralize around SpotX-Bash?

Is there anything that SpotX-Mac provides that the other doesn't?

**Comment by eatmyaspirin** [comment]
> [SpotX-Official/SpotX-Bash](https://github.com/SpotX-Official/SpotX-Bash)
> 
> This project works on Mac + Linux for latest version. Confirmed both on Apple Silicon + Intel.
> 
> @Nuzair46 no disrespect- thank you for all your work here- but wondering why continue to support this fork and not centralize around SpotX-Bash?
> 
> Is there anything that SpotX-Mac provides that the other doesn't?

The repo code hasn't been updated since jetfir3 started SpotX-Bash. See the SpotX-Mac repo history here which seems to mostly be jetfir3 - https://github.com/Nuzair46/SpotX-Mac/commits/main

**Comment by Nuzair46** [comment]
@eatmyaspirin Dude, SpotX-Mac was working until couple of weeks ago. 
Nothing against jetfire as he helped a lot on this repo, but nobody is claiming anything here, Infact he is still mentioned in the readme for his contributions. I started this port a while back to bring SpotX for mac and I was more than thankful to Jetfire for the contributions he did after (during when i was busy with other projects and work). If you were on discord, you probably know the whole drama and we want to put an end to this. Im not entitled to work on this repo and I have announced how I feel about Spotify patches in general in the past on discord (icymi, I really dont feel like spending time on these after all that drama). I might update this repo or may not. You are free to contribute if you want. But I really lost my interest after being in this scene for 5 years maintaining and contributing however I can (If you doubt it, look at BlockTheSpot repo, and If not for my initiative for SpotX-Mac, we would not be having a patch until someone thought of it). tbh, i just don't have the motivation to work on these. And some people who use these patches like BlockTheSpot/SpotX are one of the most entitled and toxic community I've came across for an open source project which really puts me to question if I should be doing this or not.

I don't like promoting amd64fox's SpotX or Jetfire's SpotX-Bash after I got blocked to contribute because of a dispute over a logo. But here I'm still maintaining the repo's and providing support on discord for the people who still use it. Please stop this, I hope the drama doesn't come over to Github.

**Comment by vantough** [comment]
hey man this bs repo code hasn't been updated since jetfir3 (og creator of this repo) started SpotX-BashSee the SpotX-Mac repo history here which seems to mostly be jetfir3 - https://github.com/Nuzair46/SpotX-Mac/commits/main (check)

I'm not sure why people are still using this repo

**Comment by Nuzair46** [comment]
Oh wow. There is no point discussing this here with you all. You clearly don't know how to differentiate an initial commit. Nobody is asking you to use this. Its upto you. But please take your nonsense somewhere else.

**Comment by Nuzair46** [comment]
Fixed

**Comment by jetfir3** [comment]
> Fixed

Your "fix" was taking all the exact ad patches from https://github.com/SpotX-Official/SpotX-Bash while also removing any mention of credits + adding your own name to the script now? 

Nice work.

**Comment by Nuzair46** [comment]
@jetfir3 funny you mention that after you make the exact clone for the repo. Please don't mention how many commits you made. I know you did a lot. But figuring out for days to port either BlockTheSpot or SpotX was hard and if not for the initial commit done here, Im pretty sure a mac port would still not be released as many used to think it was impossible. Sorry not sorry. But you should've realised what you did when you created a new repo instead of forking, without crediting the original idea.
